export const tokens = [
  {
    id: "spacex",
    name: "SpaceX",
    symbol: "SPCX",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2e/SpaceX_logo_black.svg", // Using placeholder or text for logo later
    price: 94.50,
    priceChange: 4.2,
    impliedVal: "180B",
    markPrice: 92.10,
    markVal: "175B",
    allTimeVol: "1.2M",
    liquidity: "450K",
    address: "0x123...abc",
  },
  {
    id: "openai",
    name: "OpenAI",
    symbol: "OAI",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    price: 150.20,
    priceChange: -1.5,
    impliedVal: "86B",
    markPrice: 152.00,
    markVal: "87B",
    allTimeVol: "3.4M",
    liquidity: "1.1M",
    address: "0x456...def",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    symbol: "ANTH",
    logo: "",
    price: 45.30,
    priceChange: 8.4,
    impliedVal: "18B",
    markPrice: 41.50,
    markVal: "16B",
    allTimeVol: "800K",
    liquidity: "250K",
    address: "0x789...ghi",
  },
  {
    id: "anduril",
    name: "Anduril",
    symbol: "AND",
    logo: "",
    price: 65.10,
    priceChange: 2.1,
    impliedVal: "14B",
    markPrice: 64.00,
    markVal: "13.8B",
    allTimeVol: "500K",
    liquidity: "150K",
    address: "0xabc...123",
  },
  {
    id: "kalshi",
    name: "Kalshi",
    symbol: "KLS",
    logo: "",
    price: 12.00,
    priceChange: 0.5,
    impliedVal: "1B",
    markPrice: 11.90,
    markVal: "990M",
    allTimeVol: "100K",
    liquidity: "50K",
    address: "0xdef...456",
  },
  {
    id: "polymarket",
    name: "Polymarket",
    symbol: "POLY",
    logo: "",
    price: 8.50,
    priceChange: -4.2,
    impliedVal: "500M",
    markPrice: 8.80,
    markVal: "520M",
    allTimeVol: "300K",
    liquidity: "80K",
    address: "0xghi...789",
  },
  {
    id: "stripe",
    name: "Stripe",
    symbol: "STRP",
    logo: "",
    price: 55.40,
    priceChange: 1.2,
    impliedVal: "65B",
    markPrice: 54.90,
    markVal: "64B",
    allTimeVol: "2.1M",
    liquidity: "900K",
    address: "0xjkl...012",
  },
  {
    id: "chime",
    name: "Chime",
    symbol: "CHM",
    logo: "",
    price: 32.10,
    priceChange: -0.8,
    impliedVal: "25B",
    markPrice: 32.50,
    markVal: "25.5B",
    allTimeVol: "600K",
    liquidity: "200K",
    address: "0xmno...345",
  }
];

export const ecosystemPartners = [
  {
    name: "BNB Chain",
    description: "High-performance blockchain for decentralized applications.",
    tags: ["Chain"],
    status: "LIVE",
  },
  {
    name: "Ethena",
    description: "Synthetic dollar protocol built on Ethereum.",
    tags: ["Stablecoin", "Yield"],
    status: "LIVE",
  },
  {
    name: "Allocations",
    description: "Private market investment platform for funds and SPVs.",
    tags: ["RWA"],
    status: "COMING SOON",
  },
  {
    name: "United Stables",
    description: "Decentralized stablecoin issuance protocol.",
    tags: ["Stablecoin"],
    status: "LIVE",
  },
  {
    name: "World Liberty Financial",
    description: "DeFi lending protocol and yield optimizer.",
    tags: ["Trading", "Yield"],
    status: "COMING SOON",
  },
];

export const auctions = [
  {
    id: "auc-1",
    name: "SpaceX Series F",
    status: "open",
    currentAmount: "$4.5M",
    reserve: "$5.0M",
    bids: 24,
    endDate: "2026-05-20T12:00:00Z",
  },
  {
    id: "auc-2",
    name: "OpenAI Employee Pool",
    status: "open",
    currentAmount: "$1.2M",
    reserve: "$1.0M",
    bids: 18,
    endDate: "2026-05-18T15:30:00Z",
  },
  {
    id: "auc-3",
    name: "Anthropic Early Stage",
    status: "paused",
    currentAmount: "$800K",
    reserve: "$1.5M",
    bids: 5,
    endDate: "2026-05-25T00:00:00Z",
  },
  {
    id: "auc-4",
    name: "Stripe Secondary",
    status: "open",
    currentAmount: "$10.5M",
    reserve: "$10.0M",
    bids: 56,
    endDate: "2026-05-15T18:00:00Z",
  },
  {
    id: "auc-5",
    name: "Anduril Growth",
    status: "completed",
    currentAmount: "$3.2M",
    reserve: "$2.5M",
    bids: 31,
    endDate: "2026-05-10T12:00:00Z",
  },
  {
    id: "auc-6",
    name: "Kalshi Seed",
    status: "closed",
    currentAmount: "$500K",
    reserve: "$800K",
    bids: 12,
    endDate: "2026-05-01T00:00:00Z",
  },
];
